#ifndef OPCODE_H
#define OPCODE_H

enum opcode {
    OPCODE_PROGRAM_END = -1,
    OPCODE_POINTER_INC,
    OPCODE_POINTER_DEC,
    OPCODE_VALUE_INC,
    OPCODE_VALUE_DEC,
    OPCODE_VALUE_PRINT,
    OPCODE_VALUE_READ,
    OPCODE_LOOP_BEGIN,
    OPCODE_LOOP_END,
    OPCODE_DEBUG
};

#endif
